import { Bot, BrainCircuit, Check, Eye, Gauge, Layers3, TriangleAlert, Wrench, X } from "lucide-react";
import type { ModelCapability } from "@/lib/model-capabilities";
import { StatusBadge } from "./status-badge";

function tps(value?: number | null) { return typeof value === "number" && Number.isFinite(value) ? value.toFixed(1) : "n/a"; }
function Capability({ icon: Icon, label, value, enabled = true }: { icon: React.ComponentType<{ className?: string }>; label: string; value: string; enabled?: boolean }) { return <div className="flex min-w-0 items-center gap-2"><Icon className={`h-3.5 w-3.5 shrink-0 ${enabled ? "text-[#21d4fd]" : "text-[#46566b]"}`} /><div className="min-w-0"><div className="text-[11px] text-[#617083]">{label}</div><div className="truncate text-xs text-[#cdd7e3]">{value}</div></div></div>; }

export function ModelCapabilityMatrix({ capabilities }: { capabilities: ModelCapability[] }) {
  return <section className="space-y-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-sm text-[#21d4fd]">Models</div><h1 className="mt-1 text-2xl font-semibold text-white">Serving library</h1><p className="mt-1 text-sm text-[#8a98aa]">Runtime readiness, measured performance, and Codex compatibility.</p></div><div className="text-xs text-[#617083]">{capabilities.length} installed model{capabilities.length === 1 ? "" : "s"}</div></div><div className="grid gap-3 xl:grid-cols-2">{capabilities.map((model) => <article key={model.name} className={`rounded-xl bg-[#0d141e] p-4 ${model.active ? "ring-1 ring-[#21d4fd]/45" : ""}`}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#172331]"><Bot className="h-5 w-5 text-[#21d4fd]" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2">{model.active ? <StatusBadge tone="success">active</StatusBadge> : model.served ? <StatusBadge tone="info">available</StatusBadge> : <StatusBadge tone="neutral">installed</StatusBadge>}<StatusBadge tone={model.codex === "ready" ? "success" : model.codex === "check" ? "warning" : "danger"}>Codex {model.codex}</StatusBadge></div><h2 className="mt-2 truncate text-sm font-semibold text-white" title={model.name}>{model.name}</h2>{model.alias ? <div className="mt-1 truncate font-mono text-[11px] text-[#617083]">{model.alias}</div> : null}</div></div><div className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 sm:grid-cols-4"><Capability icon={Gauge} label="Context" value={model.maxContext.toLocaleString()} /><Capability icon={Layers3} label="MTP" value={model.mtp ? "Configured" : "Not configured"} enabled={model.mtp} /><Capability icon={Eye} label="Vision" value={model.vision ? "Detected" : "Text only"} enabled={model.vision} /><Capability icon={Wrench} label="Tools" value={model.toolCalling} enabled={model.toolCalling !== "unknown"} /><Capability icon={BrainCircuit} label="Reasoning" value={model.reasoning} /><Capability icon={Gauge} label="Prompt" value={`${tps(model.bestPromptTps)} tok/s`} enabled={model.bestPromptTps != null} /><Capability icon={Gauge} label="Decode" value={`${tps(model.bestDecodeTps)} tok/s`} enabled={model.bestDecodeTps != null} /><Capability icon={model.verified ? Check : X} label="Evidence" value={model.verified ? "Benchmarked" : model.detected ? "Runtime detected" : "Configured"} enabled={model.verified} /></div>{model.knownIssue ? <div className="mt-4 flex gap-2 rounded-md bg-[#211a13] px-3 py-2 text-xs leading-5 text-[#d9b877]"><TriangleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0" />{model.knownIssue}</div> : null}</article>)}</div></section>;
}
